apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PREFIX-transcoder
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $PREFIX-transcoder
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-env: raindrop/data/$ENV/raindrop-transcoder
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "raindrop/data/$ENV/raindrop-transcoder" -}}
          {{- range $k, $v := .Data.data }}
          export {{ $k }}={{ $v }}
          {{- end -}}
          {{- end -}}
        vault.hashicorp.com/role: $NAMESPACE
        vault.hashicorp.com/tls-skip-verify: "true"
      labels:
        app: $PREFIX-transcoder
    spec:
      containers:
        - name: transcoder
          image: cme-harbor.int.bobbygeorge.dev/raindrop/raindrop-transcoder:$TAG
